<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>{{ $post->seo_title ?? $post->title }} - Elkris Bio Health</title>
<style>
    @page { margin: 40px 50px; }
    body {
        font-family: 'DejaVu Sans', sans-serif;
        font-size: 12pt;
        line-height: 1.8;
        color: #1a1c1b;
    }
    h1 {
        font-size: 26pt;
        color: #002819;
        margin-bottom: 6px;
        line-height: 1.3;
    }
    .meta {
        font-size: 10pt;
        color: #717973;
        margin-bottom: 8px;
    }
    .divider {
        border: none;
        border-top: 2px solid #086878;
        margin: 20px 0;
    }
    @if($post->featured_image)
    .featured-image {
        margin: 16px 0;
        text-align: center;
    }
    .featured-image img {
        max-width: 100%;
        max-height: 300px;
        border-radius: 8px;
    }
    .featured-image .caption {
        font-size: 9pt;
        color: #717973;
        margin-top: 4px;
    }
    @endif
    .content {
        margin-top: 20px;
    }
    h2 {
        font-size: 20pt;
        color: #002819;
        margin-top: 28px;
        margin-bottom: 12px;
        font-family: 'DejaVu Sans', sans-serif;
    }
    h3 {
        font-size: 16pt;
        color: #002819;
        margin-top: 24px;
        margin-bottom: 10px;
        font-family: 'DejaVu Sans', sans-serif;
    }
    p {
        margin-bottom: 14px;
        text-align: justify;
    }
    ul, ol {
        margin-bottom: 14px;
        padding-left: 28px;
    }
    ul { list-style-type: disc; }
    ol { list-style-type: decimal; }
    li { margin-bottom: 6px; }
    blockquote {
        border-left: 4px solid #086878;
        padding-left: 18px;
        margin: 20px 0;
        color: #404943;
        font-style: italic;
    }
    img {
        max-width: 100%;
        height: auto;
        margin: 16px 0;
    }
    a { color: #086878; text-decoration: underline; }
    pre {
        background: #e8e8e6;
        padding: 14px;
        border-radius: 4px;
        font-size: 10pt;
        overflow-x: auto;
        margin-bottom: 14px;
        font-family: 'DejaVu Sans Mono', monospace;
    }
    code {
        font-size: 10pt;
        font-family: 'DejaVu Sans Mono', monospace;
    }
    .footer {
        margin-top: 40px;
        padding-top: 16px;
        border-top: 1px solid #c0c9c1;
        font-size: 9pt;
        color: #717973;
        text-align: center;
    }
    .page-break { page-break-before: always; }
</style>
</head>
<body>
    <h1>{{ $post->title }}</h1>

    <div class="meta">
        @if($post->author)
        Written by {{ $post->author->name }} &bull;
        @endif
        Published {{ $post->published_at?->format('F j, Y') }}
        @if($post->category)
        &bull; {{ $post->category->name }}
        @endif
    </div>

    @if($post->featured_image)
    <div class="featured-image">
        <img src="{{ Storage::url($post->featured_image) }}" alt="{{ $post->featured_image_caption ?? $post->title }}">
        @if($post->featured_image_caption)
        <div class="caption">{{ $post->featured_image_caption }}</div>
        @endif
    </div>
    @endif

    <hr class="divider">

    <div class="content">
        {!! $post->body !!}
    </div>

    @if($post->excerpt)
    <div class="footer">
        <p>{{ $post->excerpt }}</p>
    </div>
    @endif

    <div class="footer">
        Generated by Elkris Bio Health Nigeria Limited &bull; {{ date('F j, Y') }}
    </div>
</body>
</html>